defmodule Faction.Extract do
  @moduledoc """
  Turns one BEAM into rows, keyed by relation name.

  Extraction needs only the BEAM and its source file, never another BEAM, so
  BEAMs can be processed independently and in parallel.
  """

  alias Faction.Beam
  alias Faction.Calls
  alias Faction.Source

  @typedoc "Rows of one BEAM, in a fixed order, keyed by relation name."
  @type rows() :: %{atom() => list(map())}

  @doc """
  Extracts the rows of the BEAM at `path`. `root` is the repository root.

  Also returns the behaviours whose callbacks the second pass should read:
  those the module declares, and the module itself when it is a behaviour.
  """
  @spec rows(path :: Path.t(), root :: Path.t()) ::
          {:ok, rows(), list(module())} | {:error, String.t()}
  def rows(path, root) do
    with {:ok, beam} <- Beam.read(path) do
      behaviours =
        if {:behaviour_info, 1} in beam.exports do
          [beam.module | beam.behaviours]
        else
          beam.behaviours
        end

      {:ok, beam_rows(beam, root), behaviours}
    end
  end

  @spec beam_rows(beam :: Beam.t(), root :: Path.t()) :: rows()
  defp beam_rows(beam, root) do
    module = Beam.module_name(beam.module)
    path = relative_path(beam.file, root)
    source = path && read_source(beam.file)

    module_row =
      cond do
        # Source outside the repository: generated by a dependency's macro.
        is_nil(path) ->
          module_row(module, true, nil, nil, nil)

        is_nil(source) ->
          module_row(module, false, path, beam.line, nil)

        end_line = Source.module_end_line(source, beam.line) ->
          module_row(module, false, path, beam.line, end_line)

        true ->
          module_row(module, true, path, beam.line, beam.line)
      end

    {function_calls, dynamic_function_calls} = Calls.rows(beam, &locate(&1, &2, path, beam, root))

    Map.merge(Faction.Ecto.rows(beam), %{
      modules: [module_row],
      functions: function_rows(beam, module, path, source),
      function_calls: function_calls,
      dynamic_function_calls: dynamic_function_calls,
      behaviours:
        beam.behaviours
        |> Enum.map(&%{module: module, behaviour: Beam.module_name(&1)})
        |> Enum.sort_by(& &1.behaviour)
    })
  end

  @spec read_source(file :: Path.t()) :: Source.t() | nil
  defp read_source(file) do
    case Source.read(file) do
      {:ok, source} -> source
      :error -> nil
    end
  end

  # A definition injected with `quote location: :keep` records the file the
  # quote was written in, and the lines of its calls refer to that file.
  # Everything else is in the module's own file. Line 0 means no line.
  @spec locate(
          definition_meta :: keyword(),
          meta :: keyword(),
          path :: String.t() | nil,
          beam :: Beam.t(),
          root :: Path.t()
        ) ::
          Calls.location()
  defp locate(definition_meta, meta, path, beam, root) do
    line =
      case meta[:line] do
        line when is_integer(line) and line > 0 -> line
        _none -> nil
      end

    path =
      case definition_meta[:file] do
        {file, _line} when is_binary(file) ->
          relative_path(Path.expand(file, beam.compile_dir), root)

        _not_kept ->
          path
      end

    if path do
      {path, line}
    else
      {nil, nil}
    end
  end

  @spec module_row(
          module :: String.t(),
          generated? :: boolean(),
          path :: String.t() | nil,
          start_line :: pos_integer() | nil,
          end_line :: pos_integer() | nil
        ) :: map()
  defp module_row(module, generated?, path, start_line, end_line) do
    %{
      module: module,
      is_generated: generated?,
      path: path,
      start_line: start_line,
      end_line: end_line
    }
  end

  @spec function_rows(
          beam :: Beam.t(),
          module :: String.t(),
          path :: String.t() | nil,
          source :: Source.t() | nil
        ) ::
          list(map())
  defp function_rows(beam, module, path, source) do
    defined =
      Enum.map(beam.definitions, fn {{name, arity}, kind, _meta, _clauses} = definition ->
        owner = default_owner(definition, beam.definitions) || definition
        {function, arity} = Beam.compiled_name(kind, name, arity)
        %{definition_row(owner, module, path, source) | function: function, arity: arity}
      end)

    defined_names =
      MapSet.new(beam.definitions, fn {name_arity, _kind, _meta, _clauses} -> name_arity end)

    # Functions the compiler adds after expansion, such as module_info/1 and __info__/1.
    added =
      for {name, arity} <- beam.exports,
          not MapSet.member?(defined_names, {name, arity}),
          not String.starts_with?(Atom.to_string(name), "MACRO-") do
        %{
          module: module,
          function: Atom.to_string(name),
          arity: arity,
          visibility: "public",
          is_generated: true,
          path: nil,
          start_line: nil,
          end_line: nil
        }
      end

    Enum.sort_by(defined ++ added, &{&1.function, &1.arity})
  end

  # A default argument compiles to extra, shorter arities (marked with the
  # :elixir_def context); they share the range of the definition declaring the
  # defaults.
  @spec default_owner(definition :: Beam.definition(), definitions :: list(Beam.definition())) ::
          Beam.definition() | nil
  defp default_owner({{name, arity}, kind, meta, _clauses}, definitions) do
    if meta[:context] == :elixir_def do
      Enum.find(definitions, fn {{owner_name, owner_arity}, owner_kind, owner_meta, _clauses} ->
        defaults = owner_meta[:defaults] || 0

        owner_name == name and owner_kind == kind and owner_arity - defaults <= arity and
          arity < owner_arity
      end)
    end
  end

  @spec definition_row(
          definition :: Beam.definition(),
          module :: String.t(),
          path :: String.t() | nil,
          source :: Source.t() | nil
        ) :: map()
  defp definition_row({{name, arity}, kind, meta, clauses}, module, path, source) do
    {function, arity} = Beam.compiled_name(kind, name, arity)
    marked_generated? = generated_meta?(meta)

    # A declared function can gain clauses from macros, e.g. a catch-all
    # added by @before_compile; only its declared clauses give its range.
    positions =
      [meta | Enum.map(clauses, &elem(&1, 0))]
      |> Enum.reject(&(not marked_generated? and generated_meta?(&1)))
      |> Enum.map(&{&1[:line], &1[:column]})
      |> Enum.reject(fn {line, _column} -> is_nil(line) end)

    declared_end_lines = declared_end_lines(source, positions, marked_generated?)
    # Outside the repository there is no application declaration at all.
    generated? =
      marked_generated? or is_nil(path) or (source != nil and Enum.empty?(declared_end_lines))

    {start_line, end_line} =
      line_range(path, positions, generated?, meta[:line], declared_end_lines)

    %{
      module: module,
      function: function,
      arity: arity,
      visibility: visibility(kind),
      is_generated: generated?,
      path: start_line && path,
      start_line: start_line,
      end_line: end_line
    }
  end

  # Code from a quote carries its context (the quoting module); default
  # argument arities carry :elixir_def but are declared.
  @spec generated_meta?(meta :: keyword()) :: boolean()
  defp generated_meta?(meta),
    do: meta[:generated] == true or meta[:context] not in [nil, :elixir_def]

  # End lines of the source definitions whose heads sit at the clause positions.
  @spec declared_end_lines(
          source :: Source.t() | nil,
          positions :: list(Source.position()),
          marked_generated? :: boolean()
        ) :: list(pos_integer())
  defp declared_end_lines(nil, _positions, _marked_generated?), do: []
  defp declared_end_lines(_source, _positions, true), do: []

  defp declared_end_lines(source, positions, false) do
    for position <- positions, end_line = source.definitions[position], do: end_line
  end

  @spec line_range(
          path :: String.t() | nil,
          positions :: list(Source.position()),
          generated? :: boolean(),
          line :: pos_integer() | nil,
          declared_end_lines :: list(pos_integer())
        ) :: {pos_integer() | nil, pos_integer() | nil}
  defp line_range(path, positions, generated?, line, declared_end_lines) do
    cond do
      is_nil(path) or Enum.empty?(positions) -> {nil, nil}
      generated? -> {line, line}
      Enum.empty?(declared_end_lines) -> {first_line(positions), nil}
      true -> {first_line(positions), Enum.max(declared_end_lines)}
    end
  end

  @spec first_line(positions :: list(Source.position())) :: pos_integer()
  defp first_line(positions) do
    positions
    |> Enum.map(fn {line, _column} -> line end)
    |> Enum.min()
  end

  @spec visibility(kind :: atom()) :: String.t()
  defp visibility(kind) when kind in [:def, :defmacro], do: "public"
  defp visibility(_kind), do: "private"

  # The path of `file` relative to the repository root, or nil when it is not
  # application source: outside the root, or in the root's deps/ or _build/
  # (dependency source, e.g. of a module a dependency's macro defines).
  @spec relative_path(file :: Path.t(), root :: Path.t()) :: String.t() | nil
  defp relative_path(file, root) do
    root = Path.expand(root)
    file = Path.expand(file)

    case Path.relative_to(file, root) do
      ^file -> nil
      "deps/" <> _dependency -> nil
      "_build/" <> _build -> nil
      relative -> relative
    end
  end
end
